# Generated by Django 3.0.8 on 2020-08-16 16:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stocktracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
