# Generated by Django 3.1.7 on 2021-03-18 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocktracker', '0003_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=5), max_length=5),
        ),
    ]
